In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [82]:
df_1 = pd.read_csv('IPO.csv')
df_1['Company Name']

0             Latent  View Analytics Limited
1               Sapphire Foods India Limited
2                                      Paytm
3                              Policy Bazaar
4                     SJS enterprise limited
5                 Sigachi Industries Limited
6                 Fino Payments Bank Limited
7                                      Nykaa
8                  Aditya Birla Sun Life AMC
9                    Paras Space and Defence
10              Sansera  Engineering Limited
11         Vijaya Diagnostics Center Limited
12                      Ami Organics Limited
13        Aptus Value Housing Finance India
14                  Chemplast Sanmar Limited
15                     CarTrade Tech Limited
16         Nuvoco Vistas Corporation Limited
17    Devyani International Limited Pizzahut
18                   Windlas Biotech Limited
19                Krsnaa Diagnostics Limited
20                      Exxaro Tiles Limited
21                               Rolex Rings
22             Glenmark Life Science Limited
23             Tatva Chintan Pharma Chem Ltd
24                                    Zomato
25                      GR Infraprojects Ltd
26          Clean Science and Technology Ltd
27                      India Pestisides Ltd
28                       Dodla Dairy Limited
29      Krishna Institute of Medical Science
30        shyam Metallics and Energy Limited
31                    Sona BLW precision Ltd
32           Suryoday Small Finance Bank Ltd
33              Macrotech Developers Limited
34                Kalyan Jewellers India Ltd
35                       Barbeque Nation Ltd
36                   Nazara Technologies Ltd
37                  Craftsman Automation Ltd
38              Laxmi Organic Industries Ltd
39                  Anupam Rasayan India Ltd
40                    Easy Trip Planners Ltd
41                     MTAR Technologies Ltd
42                   Heranaba Industries Ltd
43             Railtel Corporation India Ltd
44                                Nureca Ltd
45                           Stove Kraft Ltd
46                Home First Finance Company
47             Indian Railways Finance corp
48                             Indigo Paints
49                               Burger King
Name: Company Name, dtype: object

In [87]:
df = df_1.drop('Company Name',axis=1)
a.drop('Employee',axis=1,inplace=True)

In [88]:
X = a.drop('Listing Day gain',axis=1)
y = a['Listing Day gain']

In [28]:
y

0     148.10
1       4.04
2     -27.44
3      22.68
4      -5.87
5     267.18
6      -5.74
7      96.27
8      -1.97
9     181.40
10      9.95
11     16.20
12     53.20
13     -0.28
14     -0.92
15     -7.85
16     -7.19
17     36.22
18    -11.74
19      2.52
20     10.25
21     29.67
22      3.61
23    113.50
24     64.87
25    107.64
26     75.89
27     15.64
28     42.29
29     19.70
30     22.71
31     24.12
32    -10.80
33     -5.77
34    -14.54
35     17.56
36     44.60
37     -5.03
38     26.19
39     -6.58
40     10.43
41     87.62
42     31.74
43     28.19
44     61.44
45     13.88
46      0.87
47     -4.62
48    110.00
49    130.70
Name: Listing Day gain, dtype: float64

In [92]:
X

,Retail Investors,Qualified Investors,Non Instititional,Total,Company Name_Aditya Birla Sun Life AMC,Company Name_Ami Organics Limited,Company Name_Anupam Rasayan India Ltd,Company Name_Aptus Value Housing Finance India,Company Name_Barbeque Nation Ltd,Company Name_Burger King,...,Company Name_Sapphire Foods India Limited,Company Name_Sigachi Industries Limited,Company Name_Sona BLW precision Ltd,Company Name_Stove Kraft Ltd,Company Name_Suryoday Small Finance Bank Ltd,Company Name_Tatva Chintan Pharma Chem Ltd,Company Name_Vijaya Diagnostics Center Limited,Company Name_Windlas Biotech Limited,Company Name_Zomato,Company Name_shyam Metallics and Energy Limited
0,123.84,150.82,881.96,338.51,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7.76,7.50,3.46,6.45,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1.72,2.88,0.25,1.95,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3.45,27.52,8.15,17.86,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.41,1.45,2.36,1.63,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,80.49,86.51,172.43,101.91,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,5.92,1.65,0.21,2.03,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,12.29,92.17,112.51,82.42,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,3.24,10.36,4.39,5.25,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,118.44,175.39,973.99,318.04,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,3.15,26.47,11.37,11.47,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1.09,13.07,1.32,4.54,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,13.42,86.02,155.44,64.59,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,1.35,32.41,33.91,17.20,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
14,2.34,2.75,1.05,2.21,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,2.75,35.45,41.00,20.29,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0.74,4.40,0.67,1.74,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,39.52,95.27,213.06,116.71,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,24.54,24.10,15.91,22.56,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,42.04,49.83,116.30,64.40,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,40.10,17.67,5.36,22.68,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,24.49,143.58,360.11,130.43,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,15.00,37.30,125.62,45.07,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,35.68,186.96,516.96,182.04,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24,7.87,54.71,34.80,40.38,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
25,12.57,168.58,238.04,102.58,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,9.20,159.93,211.12,95.54,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,11.30,42.95,51.88,29.04,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,11.34,84.88,73.26,45.62,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2.90,5.26,1.89,3.84,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,11.64,153.45,339.98,120.93,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
31,1.58,3.46,0.39,2.28,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
32,3.09,2.18,1.31,2.37,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
33,0.40,3.05,1.44,1.36,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,2.82,2.76,1.91,2.61,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,13.13,5.11,3.10,5.98,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
36,75.29,103.77,389.89,175.46,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,3.44,5.21,2.84,3.82,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,20.10,175.43,217.62,106.81,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,10.77,65.74,97.42,44.06,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,70.40,77.53,382.21,159.33,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,28.40,164.99,650.79,200.79,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,11.84,67.45,271.15,83.29,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,16.78,65.14,73.25,42.39,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,166.65,3.10,31.59,39.93,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,26.04,8.02,32.72,18.03,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
46,6.59,52.53,39.00,26.66,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,3.66,3.78,2.67,3.49,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,15.93,189.57,263.05,117.02,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,68.15,86.64,354.11,156.65,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [89]:
X.shape,y.shape

((50, 54), (50,))

In [70]:
# # Functional
# inputs = tf.keras.Input(shape=(4,1))
# x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
# outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
# model_1 = tf.keras.Model(inputs=inputs, outputs=outputs)

# model_1.compile(loss=tf.keras.losses.mae,
#               optimizer=tf.keras.optimizers.Adam(),
#               metrics=["mae"])

# model_1.fit(tf.expand_dims(X,axis=-1),y,epochs=100,verbose=0)

In [102]:
# Sequential
model = tf.keras.Sequential([
        tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mae"])


model.fit(tf.expand_dims(X,axis=-1),y,epochs=100,verbose=0)

In [104]:
model.predict(tf.constant([12.1]))

WARNING:tensorflow:Model was constructed with shape (None, 54, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 54, 1), dtype=tf.float64, name='dense_29_input'), name='dense_29_input', description="created by layer 'dense_29_input'"), but it was called on an input with incompatible shape (None, 1, 1).

array([[[-1.6341437]]], dtype=float32)

In [86]:
a = pd.get_dummies(df_1)
a

,Retail Investors,Qualified Investors,Non Instititional,Employee,Total,Listing Day gain,Company Name_Aditya Birla Sun Life AMC,Company Name_Ami Organics Limited,Company Name_Anupam Rasayan India Ltd,Company Name_Aptus Value Housing Finance India,...,Company Name_Sapphire Foods India Limited,Company Name_Sigachi Industries Limited,Company Name_Sona BLW precision Ltd,Company Name_Stove Kraft Ltd,Company Name_Suryoday Small Finance Bank Ltd,Company Name_Tatva Chintan Pharma Chem Ltd,Company Name_Vijaya Diagnostics Center Limited,Company Name_Windlas Biotech Limited,Company Name_Zomato,Company Name_shyam Metallics and Energy Limited
0,123.84,150.82,881.96,4.03,338.51,148.10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7.76,7.50,3.46,NaN,6.45,4.04,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1.72,2.88,0.25,NaN,1.95,-27.44,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3.45,27.52,8.15,NaN,17.86,22.68,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.41,1.45,2.36,NaN,1.63,-5.87,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,80.49,86.51,172.43,NaN,101.91,267.18,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,5.92,1.65,0.21,0.93,2.03,-5.74,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,12.29,92.17,112.51,1.88,82.42,96.27,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,3.24,10.36,4.39,NaN,5.25,-1.97,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,118.44,175.39,973.99,NaN,318.04,181.40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,3.15,26.47,11.37,1.37,11.47,9.95,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1.09,13.07,1.32,0.98,4.54,16.20,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,13.42,86.02,155.44,NaN,64.59,53.20,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13,1.35,32.41,33.91,NaN,17.20,-0.28,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,2.34,2.75,1.05,NaN,2.21,-0.92,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,2.75,35.45,41.00,NaN,20.29,-7.85,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0.74,4.40,0.67,NaN,1.74,-7.19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,39.52,95.27,213.06,4.70,116.71,36.22,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,24.54,24.10,15.91,NaN,22.56,-11.74,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,42.04,49.83,116.30,0.98,64.40,2.52,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,40.10,17.67,5.36,2.53,22.68,10.25,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,24.49,143.58,360.11,NaN,130.43,29.67,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,15.00,37.30,125.62,NaN,45.07,3.61,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,35.68,186.96,516.96,NaN,182.04,113.50,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24,7.87,54.71,34.80,0.62,40.38,64.87,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
25,12.57,168.58,238.04,1.37,102.58,107.64,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,9.20,159.93,211.12,NaN,95.54,75.89,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,11.30,42.95,51.88,NaN,29.04,15.64,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,11.34,84.88,73.26,NaN,45.62,42.29,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2.90,5.26,1.89,1.06,3.84,19.70,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,11.64,153.45,339.98,1.55,120.93,22.71,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
31,1.58,3.46,0.39,NaN,2.28,24.12,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
32,3.09,2.18,1.31,0.34,2.37,-10.80,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
33,0.40,3.05,1.44,0.17,1.36,-5.77,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,2.82,2.76,1.91,3.74,2.61,-14.54,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,13.13,5.11,3.10,1.02,5.98,17.56,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,75.29,103.77,389.89,7.55,175.46,44.60,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,3.44,5.21,2.84,NaN,3.82,-5.03,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,20.10,175.43,217.62,NaN,106.81,26.19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,10.77,65.74,97.42,1.71,44.06,-6.58,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
40,70.40,77.53,382.21,NaN,159.33,10.43,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,28.40,164.99,650.79,NaN,200.79,87.62,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,11.84,67.45,271.15,NaN,83.29,31.74,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,16.78,65.14,73.25,3.35,42.39,28.19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,166.65,3.10,31.59,4.82,39.93,61.44,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,26.04,8.02,32.72,NaN,18.03,13.88,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
46,6.59,52.53,39.00,NaN,26.66,0.87,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,3.66,3.78,2.67,43.76,3.49,-4.62,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,15.93,189.57,263.05,2.50,117.02,110.00,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,68.15,86.64,354.11,NaN,156.65,130.70,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0